"""Build catalogue.html and gift-finder.html from index.html + pages/<name>.html.

Usage:  python tools/build_pages.py

The header, menu, footer, phone action bar and dialogs come from index.html, so they only
need editing in one place. The page content comes from pages/catalogue.html and
pages/gift-finder.html. Run this again after changing any of those files.
"""
import os
import re

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PAGES = {
    'catalogue': {
        'title': 'Product Catalogue with Prices | Madipakkam Saravana Stores',
        'description': 'Search thousands of vessels, cookware, brass, pooja items and plastics with prices at '
                       'Madipakkam Saravana Stores, Chennai. Make a list and send it on WhatsApp.',
    },
    'gift-finder': {
        'title': 'Seer &amp; Occasion Lists | Madipakkam Saravana Stores',
        'description': 'Seer varisai, housewarming, return gifts and festival lists within your budget, from real items '
                       'at Madipakkam Saravana Stores, Chennai. Send the list on WhatsApp.',
    },
}


def build(name, meta, index):
    head = index[:index.index('<main id="top">')]
    tail = index[index.index('</main>'):]

    # Page title and descriptions
    head = re.sub(r'<title>.*?</title>', f'<title>{meta["title"]}</title>', head, flags=re.S)
    for attr in ('name="description"', 'property="og:description"', 'name="twitter:description"'):
        head = re.sub(rf'(<meta {attr} content=")[^"]*', rf'\g<1>{meta["description"]}', head)
    for attr in ('property="og:title"', 'name="twitter:title"'):
        head = re.sub(rf'(<meta {attr} content=")[^"]*', rf'\g<1>{meta["title"]}', head)
    head = head.replace('https://YOUR-DOMAIN/"', f'https://YOUR-DOMAIN/{name}.html"')

    # Home-page-only parts: business details for Google, splash screen
    head = re.sub(r'\s*<!-- Business details for Google[^\n]*\n\s*<script type="application/ld\+json">.*?</script>', '', head, flags=re.S)
    head = re.sub(r'<!-- SPLASH SCREEN.*?(?=<!-- Icon sprite -->)', '', head, flags=re.S)
    head = head.replace("skip ? 'is-back' : 'is-loading'", "skip ? 'is-back' : 'js'")

    # Photo viewer dialogs only exist on the home page
    tail = re.sub(r'<!-- Lightbox -->.*?(?=<!-- "My list")', '', tail, flags=re.S)

    # Links to home-page sections ("#stores") must now point at index.html
    def home_link(m):
        target = m.group(1)
        return 'href="index.html"' if target == 'top' else f'href="index.html#{target}"'
    # (icons are <use href="#i-…"> and stay as they are)
    head = re.sub(r'href="#(?!i-)([\w-]+)"', home_link, head)
    tail = re.sub(r'href="#(?!i-)([\w-]+)"', home_link, tail)

    # Highlight this page in the menu
    head = head.replace(f'<a href="{name}.html" data-ta=', f'<a href="{name}.html" aria-current="page" data-ta=', 1)

    content = open(os.path.join(SITE, 'pages', name + '.html'), encoding='utf-8').read()
    content = re.sub(r'^<!--.*?-->\n', '', content, count=1, flags=re.S)   # drop the editing note

    html = head.replace('<!doctype html>\n', f'<!doctype html>\n<!-- Generated by tools/build_pages.py from index.html + pages/{name}.html – edit those, not this file. -->\n', 1)
    html += f'<main id="top" class="subpage subpage-{name}">\n\n{content}\n'
    html += tail
    out = os.path.join(SITE, name + '.html')
    open(out, 'w', encoding='utf-8').write(html)
    print(f'Wrote {name}.html ({len(html) // 1024} KB)')


def main():
    index = open(os.path.join(SITE, 'index.html'), encoding='utf-8').read()
    for name, meta in PAGES.items():
        build(name, meta, index)


if __name__ == '__main__':
    main()
